name: Deploy Frontend
on: workflow_run
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout
            - name: Install NodeJS
              uses: action/setup-node
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: ng build